spring:
  applicaiton:
    name: ms-jogo-personagem
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/jogo?serverTimezone=UTC
    username: root
    password: 123456
    
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    
server:
  port: 8090